extends Node

enum Mode {
	ERROR,
	DEBUG,
	RANDOM,
	RULED,
	RULED_RANDOM,
	RULED_RANDOM_ROTATION,
	BETTER_RULED_RANDOM_ROTATION,
	PERLIN,
	PERLIN_RULED,
	PERLIN_ALL_HEIGHTS,
	PERLIN_POSITIVE_HEIGHTS,
	LOWRES_PERLIN_ALL_HEIGHTS,
	LOWRES_PERLIN_POSITIVE_HEIGHTS,
}
